name: 'ci-java'
description: 'Build java project'
inputs:
  project:
    description: 'Name of project to push to'
    required: true
  zone:
    description: 'Name of zone were running in'
    required: true
  gcloud_disable_prompt:
    description: 'Turn of prompts in gcloud'
    required: false
    default: "1"
  jdk_version:
    description: "Which jdk version should we use?"
    required: true
    default: "1.11"
  service_account:
    description: "Which service account should we use"
    required: true
outputs:
  random-number:
    description: "Random number"
    value: ${{ steps.random-number-generator.outputs.random-id }}
runs:
  using: "composite"
  steps:
    - id: random-number-generator
      run: echo "::set-output name=random-id::$(echo $RANDOM)"
