name: 'ci-java'
description: 'Build java project'
inputs:
  project:
    description: 'Name of project to push to'
    required: true
  zone:
    description: 'Name of zone were running in'
    required: true
  gcloud_disable_prompt:
    description: 'Turn of prompts in gcloud'
    required: false
    default: "1"
  jdk_version:
    description: "Which jdk version should we use?"
    required: true
    default: "1.11"
  service_account:
    description: "Which service account should we use"
    required: true
outputs:
  random-number:
  value: ${{ steps.random-number-generator.outputs.random-id }}
runs:
  using: "composite"
  steps:

  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Create release IMAGE name
      run: |
        export IMAGE_NAME_FROM_REPO="$(echo "$GITHUB_REPOSITORY" | cut -d '/' -f2)"
        echo "::set-env name=IMAGE::$IMAGE_NAME_FROM_REPO"

    - name: Print environment
      run: env

    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up JDK ${{ inputs.jdk_version }}
      uses: actions/setup-java@v1
      with:
        java-version: ${{ inputs.jdk_version }}

    # Google Cloud setup
    - name: Setup GoogleCloud
      uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      with:
        version: '285.0.0'
        project_id: ${{ inputs.project }}
        service_account_email: ${{ inputs.service_account }}
        service_account_key: ${{ secrets.GCP_DOCKER_DEPLOYMENT_SA_KEY }}
        export_default_credentials: true

    - name: replace custom settings.xml to  .m2 maven directory
      run: |
        echo "Workaround as we cannot use GH_TOKEN in this setting - it does not work"
        cp ./.github/settings.xml  ~/.m2/settings.xml
